// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            Color = "#55E27A",
                            Icon = "salary",
                            Name = "Salary",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111112"),
                            Color = "#6EE7B7",
                            Icon = "freelance",
                            Name = "Freelance",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111113"),
                            Color = "#A3E635",
                            Icon = "investment",
                            Name = "Investments",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111114"),
                            Color = "#22C55E",
                            Icon = "refund",
                            Name = "Refund",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222221"),
                            Color = "#F97316",
                            Icon = "food",
                            Name = "Food",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            Color = "#38BDF8",
                            Icon = "transport",
                            Name = "Transport",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222223"),
                            Color = "#F472B6",
                            Icon = "shopping",
                            Name = "Shopping",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222224"),
                            Color = "#A78BFA",
                            Icon = "housing",
                            Name = "Housing",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222225"),
                            Color = "#FBBF24",
                            Icon = "bills",
                            Name = "Bills",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222226"),
                            Color = "#F87171",
                            Icon = "health",
                            Name = "Health",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222227"),
                            Color = "#60A5FA",
                            Icon = "education",
                            Name = "Education",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222228"),
                            Color = "#FACC15",
                            Icon = "entertainment",
                            Name = "Entertainment",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222229"),
                            Color = "#818CF8",
                            Icon = "subscriptions",
                            Name = "Subscriptions",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-22222222223a"),
                            Color = "#34D399",
                            Icon = "groceries",
                            Name = "Groceries",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-22222222223b"),
                            Color = "#2DD4BF",
                            Icon = "travel",
                            Name = "Travel",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-22222222223c"),
                            Color = "#FB7185",
                            Icon = "personal-care",
                            Name = "Personal Care",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-22222222223d"),
                            Color = "#C084FC",
                            Icon = "pets",
                            Name = "Pets",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-22222222223e"),
                            Color = "#94A3B8",
                            Icon = "taxes",
                            Name = "Taxes",
                            Type = 2
                        });
                });

            modelBuilder.Entity("api.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("api.Models.Transaction", b =>
                {
                    b.HasOne("api.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
